"""Initial migration

Revision ID: 5d101e55bb8c
Revises: 
Create Date: 2026-04-06 14:09:52.080312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d101e55bb8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('crawler_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('target_types', sa.JSON(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('debug_mode', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawler_tasks_id'), 'crawler_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_crawler_tasks_name'), 'crawler_tasks', ['name'], unique=False)
    op.create_index(op.f('ix_crawler_tasks_status'), 'crawler_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_crawler_tasks_user_id'), 'crawler_tasks', ['user_id'], unique=False)
    op.create_table('crawl_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['crawler_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_results_id'), 'crawl_results', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_results_resource_type'), 'crawl_results', ['resource_type'], unique=False)
    op.create_index(op.f('ix_crawl_results_task_id'), 'crawl_results', ['task_id'], unique=False)
    op.create_table('debug_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('request_logs', sa.JSON(), nullable=True),
    sa.Column('resource_stats', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['crawler_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debug_reports_id'), 'debug_reports', ['id'], unique=False)
    op.create_index(op.f('ix_debug_reports_task_id'), 'debug_reports', ['task_id'], unique=False)
    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('json_field', sa.String(length=100), nullable=False),
    sa.Column('web_element', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('format_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['crawler_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_mappings_id'), 'field_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_field_mappings_task_id'), 'field_mappings', ['task_id'], unique=False)
    op.create_table('intercepted_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['crawler_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercepted_resources_id'), 'intercepted_resources', ['id'], unique=False)
    op.create_index(op.f('ix_intercepted_resources_resource_type'), 'intercepted_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_intercepted_resources_task_id'), 'intercepted_resources', ['task_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('debug_info', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['crawler_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.create_index(op.f('ix_task_logs_status'), 'task_logs', ['status'], unique=False)
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_status'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_intercepted_resources_task_id'), table_name='intercepted_resources')
    op.drop_index(op.f('ix_intercepted_resources_resource_type'), table_name='intercepted_resources')
    op.drop_index(op.f('ix_intercepted_resources_id'), table_name='intercepted_resources')
    op.drop_table('intercepted_resources')
    op.drop_index(op.f('ix_field_mappings_task_id'), table_name='field_mappings')
    op.drop_index(op.f('ix_field_mappings_id'), table_name='field_mappings')
    op.drop_table('field_mappings')
    op.drop_index(op.f('ix_debug_reports_task_id'), table_name='debug_reports')
    op.drop_index(op.f('ix_debug_reports_id'), table_name='debug_reports')
    op.drop_table('debug_reports')
    op.drop_index(op.f('ix_crawl_results_task_id'), table_name='crawl_results')
    op.drop_index(op.f('ix_crawl_results_resource_type'), table_name='crawl_results')
    op.drop_index(op.f('ix_crawl_results_id'), table_name='crawl_results')
    op.drop_table('crawl_results')
    op.drop_index(op.f('ix_crawler_tasks_user_id'), table_name='crawler_tasks')
    op.drop_index(op.f('ix_crawler_tasks_status'), table_name='crawler_tasks')
    op.drop_index(op.f('ix_crawler_tasks_name'), table_name='crawler_tasks')
    op.drop_index(op.f('ix_crawler_tasks_id'), table_name='crawler_tasks')
    op.drop_table('crawler_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
